version: "3.8"
services:
  backend:
    build:
      context: ../resume-backend
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ../resume-backend:/usr/src/app
    depends_on:
      - db
    environment:
      - NODE_ENV=development  # Ensure you set the environment
      - DB_CONNECTION=pg
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=resume_user
      - DB_PASSWORD=password
      - DB_DATABASE=resume_website
      - HOST=0.0.0.0 # Add this for backend to listen on all interfaces
    command: >
      /bin/sh -c "npm install && npm run dev"
  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: resume_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resume_website
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./dbservers.json:/pgadmin4/servers.json
    depends_on:
      - db
  website-ui:
    build:
      context: ../resume-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      # - 5173:5173 for vite project only
    volumes:
      - ../resume-frontend:/app
    command: >
      /bin/sh -c "npm install && npm run start"
    restart: always

volumes:
  pgdata:
  pgadmin-data: