services:
  backend:
    build:
      context: ../resume-backend
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ../resume-backend:/usr/src/app
    depends_on:
      - db
    environment:
      - HOST=0.0.0.0
      - DB_CONNECTION=pg
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=resume_user
      - DB_PASSWORD=password
      - DB_DATABASE=resume_database
    command: >
      /bin/sh -c "npm install && npm run dev"
  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: resume_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resume_database
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./dbservers.json:/pgadmin4/servers.json
    depends_on:
      - db
  frontend:
    build:
      context: ../resume-frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ../resume-frontend:/app
    command: >
      /bin/sh -c "npm install && npm run start"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always

volumes:
  pgdata:
  pgadmin-data:
  backend-data:
  frontend-data:


